// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sumyeaysdumzyaqdsyjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1bXllYXlzZHVtenlhcWRzeWpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTk0OTYsImV4cCI6MjA2NzczNTQ5Nn0.yOJYm-YvurqzcDGGbI7Xna9Y7N2-8cku7nrPtUB_1aw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});